#
# Module manifest for module 'AzureGeneralHelperModule'
#
# Generated by: Lars Panzerbjørn
#
# Generated on: 27/07/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'AzureGeneralHelperModule.psm1'

    # Version number of this module.
    ModuleVersion = '0.1.1'

    # ID used to uniquely identify this module
    GUID = 'd3983c3a-4c8a-4792-8231-30f2b66737a0'

    # Author of this module
    Author = 'Lars Panzerbjørn'

    # Company or vendor of this module
    CompanyName = 'Ordo Ursus'

    # Copyright statement for this module
    Copyright = '(c) Lars Panzerbjørn. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Module to help with simple Azure tasks.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = 'Utility','Generic','Panzerbjrn','Azure'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Panzerbjrn/AzureGeneralHelperModule'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}

